### ISSUE TITLE
Support for SWTBot

### ISSUE THREAD

**Issue by gomesr** [rlgomes/dtf#14]
Hey would it make sense to support this? How hard would it be for me to add this to the framework? I want to try and get this in there and see if I can use it for work.

Rick

**Comment by rlgomes** [comment]
We should create a separate branch or even your own fork for this and then the first few things to get is the actual Jars that compose the swtbot (right now seems that its built into eclipse) we might be able to get the swtbot jars from the eclipse update site. 

Now some important questions about integrating this:
1. If the application is just a desktop UI application that you're testing that doesn't interact with other systems then DTF could be considered overkill because you're never going to be executing 100 parallel applications at the same time hitting some service. 
2. If you consider that writing your test will now be in XML is this advantageous to you in the sense are you going to take advantage of the ability to manipulate hundreds of tests with XSL when the product changes UI elements slightly but you don't want to have to update 100 different places manually ? or is writing in xml going to be a burdon on test devlopment ? look at the following example of java vs xml for this case:

bot.menu("File").menu("New").menu("Project...").click();
SWTBotShell shell = bot.shell("New Project");
shell.activate();
bot.tree().expandNode("Java").select("Java Project");
bot.button("Next >").click();
bot.textWithLabel("Project name:").setText("MyFirstProject"); 
bot.button("Finish").click();

would probably translate into something such as:

<xml>
<swtbot id="bot1">
    <menu name="File">
        <menu name="New">
            <menu name="New Project">
                <click/>
            </menu>
        </menu>
    </menu>
    <swtbotshell>
         <shell target="New Project"><activate/></shell>
    </swtbotshell>
    <tree>
        <expandnode>Java</expandnode>
        <select>Java Project</select>
    </tree>
    <button name="Next"><click/></button>
</swtbot>
</xml>

That would be a possible xml representation

**Comment by rlgomes** [comment]
didn't mean to close this earlier... my bad 

the example looks a bit strange because I can't embed xml correctly into these comments...

**Comment by gomesr** [comment]
The idea was just to take advantage of writing the tests in XML, not sure how much of an advantage it actually is, or if I'd be better off writing helper methods in Java, since I'm not going to take advantage of the Distributed part of DTF. And BTW swtbot has a headless build which is just a jar file you can use instead of trying to get it from eclipse, there are however some nuances in running tests using that jar.

**Comment by rlgomes** [comment]
gonna start a write up on comparing DTF to various other testing approaches and the first will be DTF vs Java, give me a day or two to finish it up but it should contain enough information for you to make a better call on what to do next. The write up will be here: https://github.com/rlgomes/dtf/wiki/Dtf-vs-the-world but let me post again to this issue once I've updated the document.

**Comment by rlgomes** [comment]
updated the page https://github.com/rlgomes/dtf/wiki/Dtf-vs-the-world with enough information on the differences between using DTF vs using a Java based framework. Now you can decide if integrating swtbot with DTF makes sense in the long run for your project. 

We can reopen this issue if you'd like to work on integrating swtbot
